on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration ExportRelease /p:Version=${VERSION}
      - name: Test
        run: dotnet test --configuration ExportRelease /p:Version=${VERSION} --no-build
      - name: Pack
        run: dotnet pack --configuration ExportRelease /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push Godot.Community.ControlBinding.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_KEY}
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
